Algoritmo "1-Idade"

Var
// Seção de Declarações das variáveis
    ano_atual, ano_nasc, idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
      escreva ("Em qual ano nos estamos?")
      leia (ano_atual)
      escreva ("Em que ano eu nasci?")
      leia (ano_nasc)

      idade  <- ano_atual - ano_nasc

      escreva ("Minha idade e:", idade)

Fimalgoritmo